### PR TITLE
deploy to Heroku

### PR DESCRIPTION
**Pull request by afeld**

### CODE REVIEW

**Comment by afeld** [comment]
It works!

https://floating-peak-18708.herokuapp.com/

Deploying to Heroku using buildpacks turned out to be tricky due to all the dependencies, so switched to using Docker. This should also make local setup a _lot_ easier. Merge if it looks good!

**Comment by afeld** [comment]
(Just FYI it looks like none of you are watching the repository.)

**Comment by alemosie** [comment]
Ah, awesome! Thanks for following up with that -- I'll merge it in now.

I'll email Sonya with the new link. After my wrap-up email yesterday, this was her reply:
"🙏🏻👍🏼💪🏼👊🏼🙏🏼🤛🏻💪🏻 I'm overcome with happiness. Already heard back from one of our organizers and she is totally stoked."

I'll keep y'all (@chrisdevwords @eeclaire, @interglobalmedia, & Dmitri, too) in the loop -- or you can provide me with an email address so that I can cc you in the communications!

**Comment by interglobalmedia** [comment]
Would love to be updated Alex! Awesome work everyone! You know my email.
It's this one. And you know where to find me on Github (if applicable!).

**Comment by afeld** [comment]
Working on getting everyone's email from @sarony - will start a thread when I do!

**Pull request merged**
